name: macOS DMG build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Make build script executable
        run: chmod +x build_macos.sh

      - name: Build app and DMG
        run: ./build_macos.sh

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPDelister-macOS
          path: |
            IPDelister-macOS.dmg
            dist/IPDelister
